### PR TITLE
Python2/3

### PR DESCRIPTION
**Pull request by Jesus89**
This PR adds compatibility to both Python 2.7 and 3.5 versions to the branch `python3` :smile: 

NOTE: this should be tested also with a real TyniFPGA B board.

### CODE REVIEW

**Comment by forensicgarlic** [comment]
why python 3.5, and not 3.6?

**Comment by tinyfpga** [comment]
I have the same question as @forensicgarlic, I noticed that @Obijuan pull request has Python 3.6, but this PR downgrades to 3.5, why is that?

**Comment by Jesus89** [comment]
Hi. There is no reason for it :trollface:. I just tested it with Python 3.5. I'll change it to 3.6 :wink:

**Comment by tinyfpga** [comment]
If you accept this PR into your repo, and then update your PR to my repo then I can accept all of these changes.

**Pull request merged**
